- name: "configure {{ component }} server"
  hosts: "{{ component }}"
  become: yes
  roles:
  - "{{ component }}"
  tasks:
    - name: print
      ansible.builtin.debug:
        msg: " {{ comment }}"