    - name: enable mysql
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: restart service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: true    

    - name: password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1