    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install node js
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Install packages based on package.json.
      community.general.npm:
        path: /app    