- name: copy service
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: restart "{{ component }}"  

- name: :sysem daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true


- name: Set ownership to roboshop
  ansible.builtin.file:
        path: /app
        owner: roboshop
        group: roboshop
        recurse: yes        