become: yes
ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.chittis.online
CATALOGUE_HOST: catalogue-dev.chittis.online
REDIS_HOST: redis-dev.chittis.online
USER_HOST: user-dev.chittis.online
CART_HOST: cart-dev.chittis.online
MYSQL_HOST: mysql-dev.chittis.online
SHIPPING_HOST: shipping-dev.chittis.online
RABBITMQ_HOST: rabbitmq-dev.chittis.online
PAYMENT_HOST: payment-dev.chittis.online


